services:
  mongodb:
    image: mongo:8
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports: ["27017:27017"]
    volumes: ["careflow360_mongo:/data/db"]
volumes:
  careflow360_mongo:
