import { Router } from 'express'; import argon2 from 'argon2'; import crypto from 'node:crypto'; import jwt from 'jsonwebtoken'; import { z } from 'zod';
import { AppError, asyncRoute, auth, ok, prisma, type AuthRequest } from '../lib.js'; import { config } from '../config.js';
export const authRouter=Router();
const sign=(u:{id:string;tenantId:string|null;isPlatform:boolean},permissions:string[])=>jwt.sign({...u,permissions},config.JWT_SECRET,{expiresIn:'15m'});
async function session(user:any){const permissions=(await prisma.userRole.findMany({where:{userId:user.id},include:{role:{include:{permissions:{include:{permission:true}}}}}})).flatMap(x=>x.role.permissions.map(p=>p.permission.key)); const raw=crypto.randomBytes(48).toString('hex'); await prisma.refreshToken.create({data:{userId:user.id,tokenHash:crypto.createHash('sha256').update(raw).digest('hex'),expiresAt:new Date(Date.now()+config.REFRESH_TOKEN_DAYS*86400000)}}); return {accessToken:sign(user,permissions),refreshToken:raw,user:{id:user.id,name:user.name,email:user.email,tenantId:user.tenantId,isPlatform:user.isPlatform,permissions}}}
authRouter.post('/login',asyncRoute(async(req,res)=>{const body=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body); const user=await prisma.user.findFirst({where:{email:body.email.toLowerCase()},include:{tenant:true}}); if(!user||!await argon2.verify(user.passwordHash,body.password))throw new AppError(401,'Invalid email or password','INVALID_CREDENTIALS'); if(user.status!=='ACTIVE')throw new AppError(403,'Account is inactive','ACCOUNT_INACTIVE'); if(user.tenant&&!['ACTIVE','TRIAL'].includes(user.tenant.status))throw new AppError(403,`Clinic account is ${user.tenant.status.toLowerCase().replaceAll('_',' ')}`,'TENANT_INACTIVE'); await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}}); return ok(res,await session(user),'Login successful')}));
authRouter.post('/refresh',asyncRoute(async(req,res)=>{const raw=z.object({refreshToken:z.string()}).parse(req.body).refreshToken; const hash=crypto.createHash('sha256').update(raw).digest('hex'); const old=await prisma.refreshToken.findUnique({where:{tokenHash:hash},include:{user:true}}); if(!old||old.revokedAt||old.expiresAt<new Date())throw new AppError(401,'Refresh token invalid','INVALID_REFRESH_TOKEN'); await prisma.refreshToken.update({where:{id:old.id},data:{revokedAt:new Date()}}); return ok(res,await session(old.user),'Session refreshed')}));
authRouter.get('/me',auth,asyncRoute(async(req:AuthRequest,res)=>ok(res,req.user)));
authRouter.post('/logout',auth,asyncRoute(async(req,res)=>{await prisma.refreshToken.updateMany({where:{userId:req.user!.id,revokedAt:null},data:{revokedAt:new Date()}});return ok(res,null,'Logged out')}));
