import { Router } from 'express'; import argon2 from 'argon2'; import crypto from 'node:crypto'; import jwt from 'jsonwebtoken'; import { z } from 'zod';
import { AppError, asyncRoute, auth, ok, prisma, type AuthRequest } from '../lib.js'; import { config } from '../config.js';
export const authRouter=Router();
const sign=(u:{id:string;tenantId:string|null;isPlatform:boolean})=>jwt.sign({id:u.id,tenantId:u.tenantId,isPlatform:u.isPlatform},config.JWT_SECRET,{expiresIn:'15m'});
export const isAdministrativeAccount=(user:any)=>user.isPlatform||Boolean(user.tenant&&user.email?.trim().toLowerCase()===user.tenant.email?.trim().toLowerCase())||user.roles?.some((entry:any)=>['SUPER_ADMIN','CLINIC_ADMIN','CLINIC_MANAGER','BRANCH_ADMIN','MANAGER'].includes(entry.role.code));
async function session(user:any){const userRoles=await prisma.userRole.findMany({where:{userId:user.id},include:{role:{include:{permissions:{include:{permission:true}}}}}});const roleCodes=[...new Set(userRoles.map(x=>x.role.code))];const configs=user.tenantId?await prisma.moduleRecord.findMany({where:{tenantId:user.tenantId,module:'roles-permissions'}}):[];const permissionRows=userRoles.flatMap(userRole=>{const configuredRole=configs.find(record=>(record.data as any)?.code===userRole.role.code);if(!configuredRole)return userRole.role.permissions.map(p=>p.permission.key);const value=(configuredRole.data as any)?.permissions;return Array.isArray(value)?value:typeof value==='string'?value.split(',').map((item:string)=>item.trim()).filter(Boolean):[]});const permissions=[...new Set(permissionRows)];const raw=crypto.randomBytes(48).toString('hex');await prisma.refreshToken.create({data:{userId:user.id,tokenHash:crypto.createHash('sha256').update(raw).digest('hex'),expiresAt:new Date(Date.now()+config.REFRESH_TOKEN_DAYS*86400000)}});return {accessToken:sign(user),refreshToken:raw,user:{id:user.id,name:user.name,email:user.email,mobile:user.mobile,tenantId:user.tenantId,isPlatform:user.isPlatform,permissions,roleCodes}}}
authRouter.post('/login',asyncRoute(async(req,res)=>{const body=z.object({email:z.string().email(),password:z.string().min(8),portal:z.enum(['ADMIN','STAFF']).default('ADMIN')}).parse(req.body); const user=await prisma.user.findFirst({where:{email:body.email.toLowerCase()},include:{tenant:true,roles:{include:{role:true}}}}); if(!user||!await argon2.verify(user.passwordHash,body.password))throw new AppError(401,'Invalid email or password','INVALID_CREDENTIALS'); if(user.status!=='ACTIVE')throw new AppError(403,'Account is inactive','ACCOUNT_INACTIVE'); if(user.tenant&&!['ACTIVE','TRIAL'].includes(user.tenant.status))throw new AppError(403,`Clinic account is ${user.tenant.status.toLowerCase().replaceAll('_',' ')}`,'TENANT_INACTIVE');const isAdmin=isAdministrativeAccount(user);if(body.portal==='ADMIN'&&!isAdmin)throw new AppError(403,'Use Staff Login for this account','WRONG_LOGIN_PORTAL');if(body.portal==='STAFF'&&isAdmin)throw new AppError(403,'Use Admin / Super Admin Login for this account','WRONG_LOGIN_PORTAL');await prisma.user.update({where:{id:user.id},data:{lastLoginAt:new Date()}}); return ok(res,await session(user),'Login successful')}));
authRouter.post('/refresh',asyncRoute(async(req,res)=>{const raw=z.object({refreshToken:z.string()}).parse(req.body).refreshToken; const hash=crypto.createHash('sha256').update(raw).digest('hex'); const old=await prisma.refreshToken.findUnique({where:{tokenHash:hash},include:{user:true}}); if(!old||old.revokedAt||old.expiresAt<new Date())throw new AppError(401,'Refresh token invalid','INVALID_REFRESH_TOKEN'); await prisma.refreshToken.update({where:{id:old.id},data:{revokedAt:new Date()}}); return ok(res,await session(old.user),'Session refreshed')}));
authRouter.get('/me',auth,asyncRoute(async(req:AuthRequest,res)=>{const user=await prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,email:true,mobile:true,tenantId:true,isPlatform:true}});if(!user)throw new AppError(404,'User account not found','NOT_FOUND');return ok(res,user)}));
authRouter.post('/logout',auth,asyncRoute(async(req,res)=>{await prisma.refreshToken.updateMany({where:{userId:req.user!.id,revokedAt:null},data:{revokedAt:new Date()}});return ok(res,null,'Logged out')}));
