import { Router } from 'express'; import argon2 from 'argon2'; import { z } from 'zod'; import { asyncRoute, ok, prisma, AppError } from '../lib.js';
import { validTokenImageSignature } from '../aisensy.js';
import sharp from 'sharp';
export const publicRouter=Router();
const xml=(value:unknown)=>String(value??'').replace(/[<>&"']/g,character=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[character]!));
publicRouter.get('/appointment-token/:id.png',asyncRoute(async(req,res)=>{
  const signature=typeof req.query.signature==='string'?req.query.signature:'';
  if(!validTokenImageSignature(req.params.id,signature))throw new AppError(403,'Invalid token image link','INVALID_SIGNATURE');
  const appointment=await prisma.appointment.findUnique({where:{id:req.params.id},include:{tenant:true,patient:true,doctor:true,department:true,branch:true}});
  if(!appointment?.token||appointment.paymentStatus!=='PAID')throw new AppError(404,'Paid appointment token not found','NOT_FOUND');
  const date=appointment.startsAt.toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'long',year:'numeric'}),time=appointment.startsAt.toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:true});
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675" viewBox="0 0 1200 675"><rect width="1200" height="675" fill="#eff6ff"/><rect x="55" y="45" width="1090" height="585" rx="28" fill="white" stroke="#bfdbfe" stroke-width="3"/><text x="100" y="115" font-family="Arial" font-size="28" font-weight="700" fill="#0f766e">${xml(appointment.tenant.name)}</text><text x="100" y="170" font-family="Arial" font-size="22" fill="#64748b">APPOINTMENT TOKEN</text><text x="100" y="285" font-family="Arial" font-size="64" font-weight="700" fill="#2563eb">${xml(appointment.token)}</text><line x1="100" y1="325" x2="1100" y2="325" stroke="#e2e8f0"/><text x="100" y="385" font-family="Arial" font-size="24" fill="#64748b">Patient</text><text x="360" y="385" font-family="Arial" font-size="25" font-weight="700">${xml(appointment.patient.name)} (${xml(appointment.patient.patientNumber)})</text><text x="100" y="435" font-family="Arial" font-size="24" fill="#64748b">Doctor</text><text x="360" y="435" font-family="Arial" font-size="25" font-weight="700">${xml(appointment.doctor.name)}</text><text x="100" y="485" font-family="Arial" font-size="24" fill="#64748b">Department</text><text x="360" y="485" font-family="Arial" font-size="25">${xml(appointment.department.name)}</text><text x="100" y="535" font-family="Arial" font-size="24" fill="#64748b">Date &amp; time</text><text x="360" y="535" font-family="Arial" font-size="25">${xml(date)} - ${xml(time)}</text><text x="100" y="585" font-family="Arial" font-size="24" fill="#64748b">Branch</text><text x="360" y="585" font-family="Arial" font-size="25">${xml(appointment.branch.name)}</text><text x="980" y="585" font-family="Arial" font-size="20" fill="#059669">PAID</text></svg>`;
  const png=await sharp(Buffer.from(svg)).png().toBuffer();
  res.type('image/png').set('Cache-Control','private, max-age=86400').send(png);
}));
publicRouter.get('/plans',asyncRoute(async(_req,res)=>ok(res,await prisma.plan.findMany({where:{status:'ACTIVE'},include:{features:{include:{feature:true}},limits:true},orderBy:{sortOrder:'asc'}}))));
publicRouter.post('/register',asyncRoute(async(req,res)=>{const b=z.object({clinicName:z.string().min(2),ownerName:z.string().min(2),email:z.string().email(),mobile:z.string().min(8),password:z.string().min(8),address:z.string().optional(),city:z.string().optional(),state:z.string().optional(),pin:z.string().optional(),planId:z.string(),billingCycle:z.enum(['MONTHLY','ANNUAL']),acceptedTerms:z.literal(true)}).parse(req.body); const plan=await prisma.plan.findUnique({where:{id:b.planId}});if(!plan)throw new AppError(400,'Selected plan does not exist','PLAN_NOT_FOUND');const exists=await prisma.user.findFirst({where:{email:b.email.toLowerCase()}});if(exists)throw new AppError(409,'Email already registered','EMAIL_EXISTS');const slug=`${b.clinicName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now().toString(36)}`;const result=await prisma.$transaction(async tx=>{const tenant=await tx.tenant.create({data:{name:b.clinicName,slug,ownerName:b.ownerName,email:b.email.toLowerCase(),mobile:b.mobile,address:b.address,city:b.city,state:b.state,pin:b.pin,status:'PENDING_APPROVAL'}});const user=await tx.user.create({data:{tenantId:tenant.id,name:b.ownerName,email:b.email.toLowerCase(),mobile:b.mobile,passwordHash:await argon2.hash(b.password)}});const role=await tx.role.create({data:{tenantId:tenant.id,name:'Clinic Admin',code:'CLINIC_ADMIN',isSystem:true}});await tx.userRole.create({data:{userId:user.id,roleId:role.id}});await tx.subscription.create({data:{tenantId:tenant.id,planId:plan.id,billingCycle:b.billingCycle,status:'PENDING'}});await tx.auditLog.create({data:{tenantId:tenant.id,actorId:user.id,action:'tenant.registered',entityType:'Tenant',entityId:tenant.id}});return tenant});return ok(res,{id:result.id,status:result.status},'Registration submitted for approval',201)}));
