import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { Activity, Building2, CalendarDays, ChevronDown, ClipboardList, Database, FileText, FlaskConical, HeartPulse, LayoutDashboard, LogOut, Menu, MessageCircle, PhoneCall, ScanLine, Settings, ShieldCheck, Stethoscope, Users, WalletCards, X } from "lucide-react";
import { api, unwrap } from "../api";

const tenant = [["Dashboard", "", LayoutDashboard], ["Enquiries / Leads", "leads", ClipboardList], ["Interested Leads", "interested-leads", HeartPulse], ["Converted Leads", "converted-leads", Users], ["Follow-ups", "followups", Activity], ["Patients", "patients", Users], ["Appointments", "appointments", CalendarDays], ["Calendar", "calendar", CalendarDays], ["Reports", "reports", FileText], ["Payments", "payments", WalletCards], ["IVR Call Logs", "call-logs", PhoneCall], ["WhatsApp", "whatsapp", MessageCircle], ["Meta Ads", "meta-ads", Activity], ["Audit Logs", "audit-logs", FileText]] as const;
const appointmentMenus = [["Doctor Appointments", "appointments", Stethoscope], ["Lab Appointments", "lab-appointments", FlaskConical], ["Radiology Appointments", "radiology-appointments", ScanLine]] as const;
const masterData = [["Settings", "settings", Settings], ["Department", "departments", Building2], ["Branches", "branches", Building2], ["Doctors", "doctors", Stethoscope], ["Doctor Schedule", "doctor-schedules", CalendarDays], ["Staff", "staff", Users], ["Roles & Permission", "roles-permissions", ShieldCheck], ["Lab", "lab", FlaskConical], ["Radiology", "radiology", ScanLine]] as const;
const admin = [["Dashboard", "", LayoutDashboard], ["Registrations", "registrations", ClipboardList], ["Tenants / Clinics", "tenants", Building2], ["Plans", "plans", WalletCards], ["Features & Limits", "features-limits", Settings], ["Subscriptions", "subscriptions", Activity], ["SaaS Invoices", "invoices", FileText], ["Transactions", "transactions", WalletCards], ["Platform Staff", "platform-staff", Users], ["Roles & Permissions", "roles-permissions", ShieldCheck], ["Usage", "usage", Activity], ["Announcements", "announcements", MessageCircle], ["AiSensy", "integrations", MessageCircle], ["Razorpay", "razorpay", WalletCards], ["Exotel", "exotel", PhoneCall], ["Audit Logs", "audit-logs", FileText], ["Platform Settings", "settings", Settings]] as const;

export function AppLayout({ mode }: { mode: "tenant" | "admin" }) {
  const location = useLocation();
  const masterDataActive = masterData.some(([, path]) => location.pathname.startsWith(`/app/${path}`));
  const appointmentsActive = appointmentMenus.some(([, path]) => location.pathname.startsWith(`/app/${path}`));
  const [open, setOpen] = useState(false), [masterOpen, setMasterOpen] = useState(masterDataActive), [appointmentsOpen, setAppointmentsOpen] = useState(appointmentsActive), navigate = useNavigate();
  useEffect(() => { if (masterDataActive) setMasterOpen(true); }, [masterDataActive]);
  useEffect(() => { if (appointmentsActive) setAppointmentsOpen(true); }, [appointmentsActive]);
  const items = mode === "admin" ? admin : tenant;
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const { data: clinic } = useQuery({ queryKey: ["clinic-profile"], queryFn: () => api.get("/crm/clinic-profile").then(unwrap), enabled: mode === "tenant" });
  const brandName = mode === "tenant" ? clinic?.name || "My Clinic" : "CareFlow360";
  const brandLogo = mode === "tenant" && clinic?.logoUrl ? clinic.logoUrl : "/logo.png";
  return <div className="shell"><aside className={open ? "sidebar open" : "sidebar"}><div className="brand"><img src={brandLogo}/><span>{brandName}</span><button className="icon mobile" onClick={() => setOpen(false)}><X/></button></div><div className="workspace"><small>{mode === "admin" ? "PLATFORM CONSOLE" : "CLINIC WORKSPACE"}</small><strong>{brandName}</strong>{mode === "tenant" && clinic?.mobile && <small>{clinic.mobile}</small>}</div><nav>{items.map(([label, path, Icon]) => mode === "tenant" && path === "appointments" ? <div key={label} className={`nav-group${appointmentsActive ? " active" : ""}`}><button type="button" className="nav-group-toggle" onClick={() => setAppointmentsOpen((value) => !value)} aria-expanded={appointmentsOpen}><CalendarDays size={18}/><span>Appointments</span><ChevronDown className={appointmentsOpen ? "expanded" : ""} size={16}/></button>{appointmentsOpen && <div className="nav-submenu">{appointmentMenus.map(([itemLabel, itemPath, ItemIcon]) => <NavLink to={itemPath} key={itemLabel} onClick={() => setOpen(false)}><ItemIcon size={16}/><span>{itemLabel}</span></NavLink>)}</div>}</div> : <NavLink end={!path} to={path} key={label} onClick={() => setOpen(false)}><Icon size={18}/><span>{label}</span></NavLink>)}{mode === "tenant" && <div className={`nav-group${masterDataActive ? " active" : ""}`}><button type="button" className="nav-group-toggle" onClick={() => setMasterOpen((value) => !value)} aria-expanded={masterOpen}><Database size={18}/><span>Master Data</span><ChevronDown className={masterOpen ? "expanded" : ""} size={16}/></button>{masterOpen && <div className="nav-submenu">{masterData.map(([label, path, Icon]) => <NavLink to={path} key={label} onClick={() => setOpen(false)}><Icon size={16}/><span>{label}</span></NavLink>)}</div>}</div>}</nav></aside><main><header className="topbar"><button className="icon" onClick={() => setOpen(true)}><Menu/></button><div className="top-search">Search patients, leads, appointments…</div><div className="avatar">{(user.name || "A")[0]}</div><div className="user"><strong>{user.name || "Administrator"}</strong><small>{mode === "admin" ? "Super Admin" : brandName}</small></div><button className="icon" title="Log out" onClick={() => { localStorage.clear(); navigate("/login"); }}><LogOut/></button></header><div className="content"><Outlet/></div></main></div>;
}
