import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { NavLink, Outlet, useNavigate } from "react-router-dom";
import { Activity, Building2, CalendarDays, ClipboardList, FileText, HeartPulse, LayoutDashboard, LogOut, Menu, MessageCircle, PhoneCall, Settings, ShieldCheck, Stethoscope, Users, WalletCards, X } from "lucide-react";
import { api, unwrap } from "../api";

const tenant = [["Dashboard", "", LayoutDashboard], ["Enquiries / Leads", "leads", ClipboardList], ["Interested Leads", "interested-leads", HeartPulse], ["Converted Leads", "converted-leads", Users], ["Follow-ups", "followups", Activity], ["Patients", "patients", Users], ["Appointments", "appointments", CalendarDays], ["Calendar", "calendar", CalendarDays], ["Doctors", "doctors", Stethoscope], ["Doctor Schedules", "doctor-schedules", CalendarDays], ["Departments", "departments", Building2], ["Branches", "branches", Building2], ["Staff", "staff", Users], ["Roles & Permissions", "roles-permissions", ShieldCheck], ["Reports", "reports", FileText], ["Payments", "payments", WalletCards], ["IVR Call Logs", "call-logs", PhoneCall], ["WhatsApp", "whatsapp", MessageCircle], ["Meta Ads", "meta-ads", Activity], ["Settings", "settings", Settings], ["Audit Logs", "audit-logs", FileText]] as const;
const admin = [["Dashboard", "", LayoutDashboard], ["Registrations", "registrations", ClipboardList], ["Tenants / Clinics", "tenants", Building2], ["Plans", "plans", WalletCards], ["Features & Limits", "features-limits", Settings], ["Subscriptions", "subscriptions", Activity], ["SaaS Invoices", "invoices", FileText], ["Transactions", "transactions", WalletCards], ["Platform Staff", "platform-staff", Users], ["Roles & Permissions", "roles-permissions", ShieldCheck], ["Usage", "usage", Activity], ["Announcements", "announcements", MessageCircle], ["AiSensy", "integrations", MessageCircle], ["Razorpay", "razorpay", WalletCards], ["Exotel", "exotel", PhoneCall], ["Audit Logs", "audit-logs", FileText], ["Platform Settings", "settings", Settings]] as const;

export function AppLayout({ mode }: { mode: "tenant" | "admin" }) {
  const [open, setOpen] = useState(false), navigate = useNavigate();
  const items = mode === "admin" ? admin : tenant;
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const { data: clinic } = useQuery({ queryKey: ["clinic-profile"], queryFn: () => api.get("/crm/clinic-profile").then(unwrap), enabled: mode === "tenant" });
  const brandName = mode === "tenant" ? clinic?.name || "My Clinic" : "CareFlow360";
  const brandLogo = mode === "tenant" && clinic?.logoUrl ? clinic.logoUrl : "/logo.png";
  return <div className="shell"><aside className={open ? "sidebar open" : "sidebar"}><div className="brand"><img src={brandLogo}/><span>{brandName}</span><button className="icon mobile" onClick={() => setOpen(false)}><X/></button></div><div className="workspace"><small>{mode === "admin" ? "PLATFORM CONSOLE" : "CLINIC WORKSPACE"}</small><strong>{brandName}</strong>{mode === "tenant" && clinic?.mobile && <small>{clinic.mobile}</small>}</div><nav>{items.map(([label, path, Icon]) => <NavLink end={!path} to={path} key={label} onClick={() => setOpen(false)}><Icon size={18}/><span>{label}</span></NavLink>)}</nav></aside><main><header className="topbar"><button className="icon" onClick={() => setOpen(true)}><Menu/></button><div className="top-search">Search patients, leads, appointments…</div><div className="avatar">{(user.name || "A")[0]}</div><div className="user"><strong>{user.name || "Administrator"}</strong><small>{mode === "admin" ? "Super Admin" : brandName}</small></div><button className="icon" title="Log out" onClick={() => { localStorage.clear(); navigate("/login"); }}><LogOut/></button></header><div className="content"><Outlet/></div></main></div>;
}
