import { createHmac, timingSafeEqual } from "node:crypto";
import { appointmentToken, decryptIntegrationSecret, sendDiagnosticMessage, sendPaymentSuccessMessage, type AppointmentMessage } from "./aisensy.js";
import { config } from "./config.js";
import { prisma } from "./lib.js";

export const CASHFREE_PROVIDER = "CASHFREE_PAYMENT_LINK";
const API_VERSION = "2023-08-01";
const apiBase = (test: boolean) => test ? "https://sandbox.cashfree.com/pg" : "https://api.cashfree.com/pg";
const phone = (value: string) => value.replace(/\D/g, "").replace(/^91(?=\d{10}$)/, "").slice(-10);
const safeId = (prefix: string, id: string) => `${prefix}_${id.replace(/[^a-zA-Z0-9_-]/g, "_")}`.slice(0, 50);

async function createLink(tenantId: string, body: Record<string, unknown>) {
  const integration = await prisma.cashfreeIntegration.findUnique({ where: { tenantId } });
  if (!integration?.isActive) throw new Error("Cashfree is not configured or active for this clinic");
  const response = await fetch(`${apiBase(integration.isTestMode)}/links`, {
    method: "POST",
    headers: { "content-type":"application/json", "x-api-version":API_VERSION, "x-client-id":integration.appId, "x-client-secret":decryptIntegrationSecret(integration.secretKeyEncrypted), "x-idempotency-key":crypto.randomUUID() },
    signal: AbortSignal.timeout(15000), body: JSON.stringify(body),
  });
  const text = await response.text();
  if (!response.ok) throw new Error(`Cashfree returned ${response.status}: ${text.slice(0, 500)}`);
  const link = JSON.parse(text) as { cf_link_id?:string|number; link_id?:string; link_url?:string; link_expiry_time?:string };
  if (!link.link_id || !link.link_url) throw new Error("Cashfree did not return a payment link");
  return { id:link.link_id, short_url:link.link_url, cfLinkId:String(link.cf_link_id||""), expiresAt:link.link_expiry_time };
}

export async function ensureCashfreePaymentLink(a:{id:string;tenantId:string;appointmentNumber:string;amount:number;patientName:string;patientMobile:string;patientEmail?:string|null}) {
  const existing=await prisma.payment.findFirst({where:{appointmentId:a.id,provider:CASHFREE_PROVIDER,status:"PENDING",paymentUrl:{not:null}},orderBy:{createdAt:"desc"}});
  if(existing?.paymentUrl)return{id:existing.providerTransactionId||existing.id,short_url:existing.paymentUrl};
  const link=await createLink(a.tenantId,{link_id:safeId("appointment",a.id),link_amount:Number(a.amount.toFixed(2)),link_currency:"INR",link_purpose:`Consultation fee for ${a.appointmentNumber}`,customer_details:{customer_name:a.patientName,customer_phone:phone(a.patientMobile),...(a.patientEmail?{customer_email:a.patientEmail}:{})},link_notify:{send_sms:false,send_email:false},link_auto_reminders:true,link_meta:{return_url:`${config.APP_URL.replace(/\/$/,"")}/payment/${encodeURIComponent(a.appointmentNumber)}`,notify_url:`${config.APP_URL.replace(/\/$/,"")}/api/cashfree/webhook`},link_notes:{tenantId:a.tenantId,appointmentId:a.id,appointmentNumber:a.appointmentNumber}});
  await prisma.payment.create({data:{tenantId:a.tenantId,appointmentId:a.id,provider:CASHFREE_PROVIDER,providerTransactionId:link.cfLinkId||link.id,paymentUrl:link.short_url,amount:a.amount,status:"PENDING",secureToken:crypto.randomUUID(),expiresAt:link.expiresAt?new Date(link.expiresAt):null}});return link;
}

export async function ensureDiagnosticPaymentLink(record:any,patient:any){const data=record.data as any;if(data.paymentUrl&&data.paymentProvider==="CASHFREE")return{id:data.paymentLinkId,short_url:data.paymentUrl};const link=await createLink(record.tenantId,{link_id:safeId("diagnostic",record.id),link_amount:Number(Number(data.amount||0).toFixed(2)),link_currency:"INR",link_purpose:`Diagnostic tests for ${record.title}`,customer_details:{customer_name:patient.name,customer_phone:phone(patient.mobile),...(patient.email?{customer_email:patient.email}:{})},link_notify:{send_sms:false,send_email:false},link_auto_reminders:true,link_meta:{return_url:`${config.APP_URL.replace(/\/$/,"")}/login`,notify_url:`${config.APP_URL.replace(/\/$/,"")}/api/cashfree/webhook`},link_notes:{tenantId:record.tenantId,diagnosticAppointmentId:record.id,appointmentNumber:record.title}});await prisma.moduleRecord.update({where:{id:record.id},data:{data:{...data,paymentProvider:"CASHFREE",paymentLinkId:link.id,paymentLinkCfId:link.cfLinkId,paymentUrl:link.short_url}}});return link}

export function verifyCashfreeSignature(rawBody:Buffer,signature:string,timestamp:string,secret:string){if(!signature||!timestamp||!/^\d+$/.test(timestamp))return false;const expected=createHmac("sha256",secret).update(timestamp).update(rawBody).digest("base64"),a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b)}

export async function confirmCashfreeDiagnostic(id:string,paymentId?:string){const record=await prisma.moduleRecord.findUnique({where:{id}});if(!record||!["lab-appointments","radiology-appointments"].includes(record.module))throw new Error("Diagnostic appointment not found");const data=record.data as any;const[patient,clinic]=await Promise.all([prisma.patient.findUnique({where:{id:data.patientId}}),prisma.tenant.findUnique({where:{id:record.tenantId!}})]);if(!patient||!clinic)throw new Error("Diagnostic patient or clinic not found");const updated=await prisma.moduleRecord.update({where:{id},data:{status:record.status==="CANCELLED"?record.status:"CONFIRMED",data:{...data,paymentStatus:"PAID",paymentConfirmedAt:new Date().toISOString(),providerPaymentId:paymentId||null}}});const message:AppointmentMessage={appointmentId:id,tenantId:record.tenantId!,appointmentNumber:record.title,patientName:patient.name,patientMobile:patient.mobile,patientNumber:patient.patientNumber,clinicName:clinic.name,clinicPhone:clinic.mobile,doctorName:record.module==="lab-appointments"?"Laboratory":"Radiology",departmentName:data.testNames||"Diagnostic test",branchName:"Clinic",startsAt:new Date(data.appointmentAt),amount:Number(data.amount||0),token:record.title};const delivery=await sendDiagnosticMessage("payment_success",message);await prisma.auditLog.create({data:{tenantId:record.tenantId!,action:`${record.module}.whatsapp.payment_success.${delivery.sent?"sent":"skipped"}`,entityType:"ModuleRecord",entityId:id,metadata:delivery}});return updated}

export async function confirmCashfreeAppointment(appointmentId:string,paymentId?:string){const full=await prisma.appointment.findUnique({where:{id:appointmentId},include:{tenant:true,patient:true,doctor:true,department:true,branch:true}});if(!full)throw new Error("Appointment not found");if(full.paymentStatus==="PAID"&&full.token)return full;const token=full.token||appointmentToken(full.doctor.name,full.department.name,full.department.code,full.startsAt,full.serialNumber||1);const appointment=await prisma.$transaction(async tx=>{const updated=await tx.appointment.update({where:{id:full.id},data:{paymentStatus:"PAID",status:"CONFIRMED",paymentConfirmedAt:new Date(),token}});await tx.payment.updateMany({where:{appointmentId:full.id,provider:CASHFREE_PROVIDER},data:{status:"PAID",providerPaymentId:paymentId||null,confirmedAt:new Date()}});await tx.auditLog.create({data:{tenantId:full.tenantId,action:"appointment.payment.cashfree_confirmed",entityType:"Appointment",entityId:full.id,metadata:{paymentId:paymentId||null,token}}});return updated});const message:AppointmentMessage={appointmentId:full.id,tenantId:full.tenantId,appointmentNumber:full.appointmentNumber,patientName:full.patient.name,patientMobile:full.patient.mobile,patientNumber:full.patient.patientNumber,clinicName:full.tenant.name,clinicPhone:full.tenant.mobile,doctorName:full.doctor.name,departmentName:full.department.name,branchName:full.branch.name,startsAt:full.startsAt,amount:full.amount,token};try{const delivery=await sendPaymentSuccessMessage(message);await prisma.auditLog.create({data:{tenantId:full.tenantId,action:`appointment.whatsapp.payment_success.${delivery.sent?"sent":"skipped"}`,entityType:"Appointment",entityId:full.id,metadata:delivery}})}catch(error){await prisma.auditLog.create({data:{tenantId:full.tenantId,action:"appointment.whatsapp.payment_success.failed",entityType:"Appointment",entityId:full.id,metadata:{error:error instanceof Error?error.message:"Unknown AiSensy error"}}})}return appointment}
