import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CalendarDays, Coins, Tag, ReceiptText, FileText, IndianRupee, Clock3, BadgeMinus } from "lucide-react";
import { bookingGroup, paymentGroup } from "./appointmentAnalytics";
import { financialRanking, financialTrend, FinancialRow } from "./accountsAnalytics";

const colors: Record<string, string> = { Paid: "#00bb91", Confirmed: "#00bb91", Pending: "#ffb84d", Refunded: "#ff3f76", Cancelled: "#ff3f76", Failed: "#9746ed", Completed: "#9746ed", "No show": "#279dff", "Partially paid": "#1aabc0", Rescheduled: "#b077ed", "Checked in": "#1aabc0", "In consultation": "#1768ff", "Not required": "#94a3b8" };
const chartDate = (date: string) => new Date(`${date.length === 7 ? date + "-01" : date}T00:00:00Z`).toLocaleDateString("en-US", { timeZone: "UTC", month: "short", ...(date.length === 7 ? { year: "2-digit" } : { day: "numeric" }) });
function StatusDonut({ title, rows, payment }: { title: string; rows: FinancialRow[]; payment?: boolean }) {
  const data = Object.entries(rows.reduce<Record<string, number>>((all, r) => { const name = payment ? paymentGroup(r.paymentStatus) : bookingGroup(r.status); all[name] = (all[name] || 0) + 1; return all; }, {})).map(([name, value]) => ({ name, value }));
  return <article className="finance-chart"><header><h2>{title}</h2><small>Selected period</small></header><div className="finance-donut"><div className="finance-ring"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={rows.length ? data : [{ name: "Empty", value: 1 }]} dataKey="value" innerRadius="65%" outerRadius="92%" startAngle={90} endAngle={-270}>{(rows.length ? data : [{ name: "Empty" }]).map((r) => <Cell key={r.name} fill={colors[r.name] || "#e9eef6"}/>)}</Pie>{!!rows.length && <Tooltip/>}</PieChart></ResponsiveContainer><div className="finance-ring-label"><strong>{rows.length}</strong><span>Total</span></div></div><ul>{data.length ? data.map((r) => <li key={r.name}><i style={{ background: colors[r.name] || "#94a3b8" }}/><span>{r.name}</span><b>{r.value} <small>({Math.round(r.value * 100 / rows.length)}%)</small></b></li>) : <li>No appointments</li>}</ul></div></article>;
}
export function AccountsSummary({ count, totals, money }: { count: number; totals: Record<string, number>; money: (value: number) => string }) {
  const cards = [["Appointments", String(count), CalendarDays, "blue"], ["Gross charges", money(totals.gross), Coins, "green"], ["Discounts", money(totals.discount), Tag, "purple"], ["Net charges", money(totals.charge), ReceiptText, "blue"], ["Billable", money(totals.billable), FileText, "purple"], ["Collected", money(totals.collected), IndianRupee, "green"], ["Refunded", money(totals.refunded), BadgeMinus, "pink"], ["Outstanding", money(totals.outstanding), Clock3, "orange"]] as const;
  return <div className="finance-summary">{cards.map(([title, value, Icon, color]) => <article key={title} className={`finance-metric finance-${color}`}><span><Icon/></span><div><small>{title}</small><strong>{value}</strong><p>Selected period</p></div></article>)}</div>;
}
export function AccountsDashboard({ rows, from, to, timezone, kind, money, currency }: { rows: FinancialRow[]; from: string; to: string; timezone: string; kind: string; money: (value: number) => string; currency: string }) {
  const [monthly, setMonthly] = useState(false), [limit, setLimit] = useState(5), [sort, setSort] = useState<"collected" | "gross" | "outstanding">("collected");
  const trend = useMemo(() => financialTrend(rows, from, to, timezone, monthly), [rows, from, to, timezone, monthly]);
  const rankings = useMemo(() => financialRanking(rows).sort((a, b) => b[sort] - a[sort] || b.gross - a.gross || a.name.localeCompare(b.name)), [rows, sort]);
  const top = rankings.slice(0, limit), noun = kind === "doctor" ? "Doctors" : "Tests / Packages";
  const collected = rows.reduce((n, r) => n + (r.netCollected || 0), 0), outstanding = rows.reduce((n, r) => n + (r.outstanding || 0), 0), total = collected + outstanding, incomplete = rows.some((r) => r.netCollected === null || r.outstanding === null);
  const collectionData = [{ name: "Net collected", value: Math.max(0, collected) }, { name: "Outstanding", value: outstanding }];
  const short = (n: number) => Math.abs(n) >= 1000 ? `${Math.round(n / 100) / 10}K` : String(n);
  return <div className="finance-charts">
    <article className="finance-chart finance-trend"><header><h2>Revenue &amp; Net Charge Trend</h2><select aria-label="Financial chart grouping" value={monthly ? "monthly" : "daily"} onChange={(e) => setMonthly(e.target.value === "monthly")}><option value="daily">Daily</option><option value="monthly">Monthly</option></select></header><div className="finance-legend"><span><i/>Gross charge</span><span><i/>Net charge</span><span><i/>Collected</span></div><div className="finance-plot"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ left: -15, right: 12, top: 10 }}><defs><linearGradient id="financeGross" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#1768ff" stopOpacity={0.25}/><stop offset="1" stopColor="#1768ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf2f8" vertical={false}/><XAxis dataKey="date" tickFormatter={chartDate} minTickGap={22} tickLine={false} axisLine={false}/><YAxis tickFormatter={short} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(v) => chartDate(String(v))} formatter={(v: any) => money(Number(v))}/><Area isAnimationActive={false} type="monotone" dataKey="gross" name="Gross charge" stroke="#1768ff" fill="url(#financeGross)" strokeWidth={2}/><Area isAnimationActive={false} type="monotone" dataKey="charge" name="Net charge" stroke="#00bb91" fill="#00bb91" fillOpacity={0.08} strokeWidth={2}/><Area isAnimationActive={false} type="monotone" dataKey="collected" name="Collected" stroke="#ff7043" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></article>
    <StatusDonut title="Payment Status" rows={rows} payment/><StatusDonut title="Appointment Status" rows={rows}/>
    <article className="finance-chart finance-performance"><header><h2>{kind === "doctor" ? "Doctor" : kind === "lab" ? "Lab Test" : "Radiology Test"} Wise Financial Performance</h2><select aria-label="Number of top services" value={limit} onChange={(e) => setLimit(Number(e.target.value))}><option value={5}>Top 5</option><option value={10}>Top 10</option></select></header><div className="finance-legend"><span><i/>Gross charge</span><span><i/>Collected</span><span><i/>Outstanding</span></div><div className="finance-plot" style={{ height: Math.max(170, top.length * 34) }}>{top.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={top} layout="vertical" margin={{ left: 0, right: 16 }}><CartesianGrid stroke="#edf2f8" horizontal={false}/><XAxis type="number" tickFormatter={short} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={135} tickFormatter={(name: string) => name.length > 23 ? name.slice(0, 22) + "…" : name} axisLine={false} tickLine={false}/><Tooltip formatter={(v: any) => money(Number(v))}/><Bar isAnimationActive={false} dataKey="gross" name="Gross charge" fill="#1768ff"/><Bar isAnimationActive={false} dataKey="collected" name="Collected" fill="#00bb91"/><Bar isAnimationActive={false} dataKey="outstanding" name="Outstanding" fill="#ffb84d"/></BarChart></ResponsiveContainer> : <p className="finance-empty">No financial records for this period.</p>}</div></article>
    <article className="finance-chart"><header><h2>Collection vs Outstanding</h2></header><div className="finance-donut"><div className="finance-ring"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={total > 0 ? collectionData : [{ name: "Empty", value: 1 }]} dataKey="value" innerRadius="65%" outerRadius="92%" startAngle={90} endAngle={-270}>{(total > 0 ? collectionData : [{ name: "Empty" }]).map((r, i) => <Cell key={r.name} fill={total > 0 ? ["#00bb91", "#ff7043"][i] : "#e9eef6"}/>)}</Pie>{total > 0 && <Tooltip formatter={(v: any) => money(Number(v))}/>}</PieChart></ResponsiveContainer><div className="finance-ring-label"><span>{currency}</span><strong className="finance-ring-money">{total.toLocaleString("en-IN", { maximumFractionDigits: 2 })}</strong><span>{incomplete ? "Known total" : "Total"}</span></div></div><ul>{collectionData.map((r, i) => <li key={r.name}><i style={{ background: ["#00bb91", "#ff7043"][i] }}/><span>{r.name}<b className="finance-amount">{money(r.value)} ({total > 0 ? Math.round(r.value * 100 / total) : 0}%)</b></span></li>)}</ul></div></article>
    <article className="finance-chart finance-top"><header><div><h2>Top Performing {noun}</h2><small>By {sort === "gross" ? "gross charges" : sort} · known amounts</small></div><select aria-label="Rank services by" value={sort} onChange={(e) => setSort(e.target.value as typeof sort)}><option value="collected">By Collected</option><option value="gross">By Gross Charge</option><option value="outstanding">By Outstanding</option></select></header><div className="table-wrap"><table><thead><tr><th>#</th><th>{kind === "doctor" ? "Doctor" : "Test / Package"}</th><th>Appointments</th><th>Collected</th><th>Outstanding</th></tr></thead><tbody>{top.map((r, i) => <tr key={r.name}><td>{i + 1}</td><td title={r.name}>{r.name}{r.incomplete && " *"}</td><td>{r.appointments}</td><td>{money(r.collected)}</td><td>{money(r.outstanding)}</td></tr>)}</tbody></table>{!top.length && <p className="finance-empty">No appointments in this period.</p>}</div></article>
  </div>;
}
