import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CalendarDays, Check, Clock3, IndianRupee, Plus, X } from "lucide-react";
import { AnalyticsAppointment, appointmentRange, appointmentTrend, summarizeAppointments } from "./appointmentAnalytics";
import "./AppointmentOverview.css";

const colors: Record<string, string> = { Confirmed: "#00bd91", Paid: "#00bd91", Pending: "#ffb54d", Cancelled: "#ff4566", Completed: "#8b45ef", Refunded: "#8b45ef", Rescheduled: "#ad66f0", "No show": "#1768ff", Failed: "#ff4566", "Partially paid": "#21a7c5", "Not required": "#94a3b8", "Checked in": "#21a7c5", "In consultation": "#1768ff" };
const palette = ["#1768ff", "#19a8c4", "#aa6beb", "#ffb54d", "#f958aa"];
const chartDate = (value: string) => new Date(`${value.length === 7 ? value + "-01" : value}T00:00:00Z`).toLocaleDateString("en-US", { timeZone: "UTC", month: "short", ...(value.length === 7 ? { year: "2-digit" } : { day: "numeric" }) });
function Donut({ title, data, total }: { title: string; data: { name: string; value: number }[]; total: number }) {
  return <article className="appointment-chart"><header><h2>{title}</h2><span>Selected period</span></header><div className="appointment-donut"><div className="appointment-donut-graphic"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={total ? data : [{ name: "No appointments", value: 1 }]} dataKey="value" innerRadius="66%" outerRadius="93%" stroke="white" startAngle={90} endAngle={-270}>{(total ? data : [{ name: "Empty" }]).map((item) => <Cell key={item.name} fill={colors[item.name] || "#e7edf7"}/>)}</Pie>{total > 0 && <Tooltip/>}</PieChart></ResponsiveContainer><div className="appointment-donut-total"><strong>{total}</strong><span>Total</span></div></div><ul>{data.length ? data.map((item) => <li key={item.name}><i style={{ background: colors[item.name] || "#94a3b8" }}/><span>{item.name}</span><b>{item.value} <small>({Math.round(item.value * 100 / total)}%)</small></b></li>) : <li>No appointments</li>}</ul></div></article>;
}
function Ranking({ title, rows }: { title: string; rows: { name: string; value: number }[] }) {
  const max = Math.max(1, ...rows.map((r) => r.value));
  return <article className="appointment-chart"><header><h2>{title}</h2><span>Top 5 · selected period</span></header><div className="appointment-ranking">{rows.length ? rows.map((row, i) => <div key={row.name}><span title={row.name}>{row.name}</span><div><i style={{ width: `${row.value * 100 / max}%`, background: palette[i] }}/></div><b>{row.value}</b></div>) : <p>No appointments in this period.</p>}</div></article>;
}
export function AppointmentOverview({ rows, from, to, onRange, onAdd, loading, failed, nameFor }: { rows: AnalyticsAppointment[]; from: string; to: string; onRange: (from: string, to: string) => void; onAdd: () => void; loading: boolean; failed: boolean; nameFor: (row: any, key: string) => string }) {
  const [preset, setPreset] = useState("Today"), [monthly, setMonthly] = useState(false);
  const summary = useMemo(() => summarizeAppointments(rows), [rows]);
  const trend = useMemo(() => appointmentTrend(rows, from, to, monthly), [rows, from, to, monthly]);
  const rank = (key: "doctorId" | "departmentId") => Object.entries(rows.reduce<Record<string, number>>((all, row) => { const name = nameFor(row, key); all[name] = (all[name] || 0) + 1; return all; }, {})).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value).slice(0, 5);
  const cards = [["Total Appointments", summary.total, CalendarDays, "blue", "in selected period"], ["Confirmed", summary.confirmed, Check, "green", "of total"], ["Pending", summary.pending, Clock3, "orange", "of total"], ["Cancelled", summary.cancelled, X, "red", "of total"], ["Completed", summary.completed, Check, "purple", "of total"], ["Revenue (Paid)", summary.revenue, IndianRupee, "teal", "paid appointment fees"]] as const;
  const grouping = <select aria-label="Chart grouping" value={monthly ? "monthly" : "daily"} onChange={(e) => setMonthly(e.target.value === "monthly")}><option value="daily">Daily</option><option value="monthly">Monthly</option></select>;
  return <>
    <header className="appointment-overview-head"><div className="appointment-heading"><span className="appointment-heading-icon"><CalendarDays/></span><div><small>Clinic Management / <b>Appointments</b></small><h1>Doctor Appointments</h1><p>Book and manage doctor appointments. View analytics, track payments and monitor daily visits.</p></div></div><div className="appointment-head-controls"><div className="appointment-range-control"><CalendarDays/><input aria-label="From appointment date" type="date" value={from} max={to || undefined} onChange={(e) => { setPreset("Custom Range"); onRange(e.target.value, to); }}/><span>–</span><input aria-label="To appointment date" type="date" value={to} min={from || undefined} onChange={(e) => { setPreset("Custom Range"); onRange(from, e.target.value); }}/></div><div className="appointment-presets">{["Today", "Yesterday", "This Month", "This Year", "Custom Range", "All Time"].map((item) => <button key={item} className={preset === item ? "active" : ""} onClick={() => { setPreset(item); if (item !== "Custom Range") { const range = appointmentRange(item); onRange(range[0], range[1]); } else document.querySelector<HTMLInputElement>('[aria-label="From appointment date"]')?.focus(); }}>{item}</button>)}</div><button className="btn" onClick={onAdd}><Plus/> Add Appointment</button></div></header>
    {loading ? <div className="state">Loading appointment analytics…</div> : failed ? <div className="state error">Unable to load appointment analytics.</div> : <>
      <div className="appointment-metrics">{cards.map(([title, value, Icon, color, note]) => <article key={title} className={`appointment-metric ap-${color}`}><span className="appointment-metric-icon"><Icon/></span><div><small>{title}</small><strong>{title === "Revenue (Paid)" ? `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}` : value.toLocaleString("en-IN")}</strong><p>{note === "of total" ? `${summary.total ? Math.round(value * 100 / summary.total) : 0}% of total` : note}</p></div></article>)}</div>
      <div className="appointment-chart-grid"><article className="appointment-chart appointment-trend"><header><h2>Appointments Trend</h2>{grouping}</header><div className="appointment-chart-legend"><span><i/>Total Appointments</span><span><i/>Completed Appointments</span></div><div className="appointment-plot"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ top: 8, right: 10, left: -22, bottom: 0 }}><defs><linearGradient id="appointmentTotal" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#1768ff" stopOpacity={0.3}/><stop offset="1" stopColor="#1768ff" stopOpacity={0}/></linearGradient><linearGradient id="appointmentCompleted" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#00bd91" stopOpacity={0.25}/><stop offset="1" stopColor="#00bd91" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf1f8" vertical={false}/><XAxis dataKey="date" tickFormatter={chartDate} minTickGap={24} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><Tooltip labelFormatter={(v) => chartDate(String(v))}/><Area isAnimationActive={false} type="monotone" dataKey="total" name="Total Appointments" stroke="#1768ff" fill="url(#appointmentTotal)" strokeWidth={2}/><Area isAnimationActive={false} type="monotone" dataKey="completed" name="Completed Appointments" stroke="#00bd91" fill="url(#appointmentCompleted)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></article>
      <Donut title="Appointments by Booking Status" data={summary.bookings} total={summary.total}/><Donut title="Appointments by Payment Status" data={summary.payments} total={summary.total}/>
      <article className="appointment-chart"><header><h2>Appointments by Date</h2><span>{monthly ? "Monthly" : "Daily"}</span></header><div className="appointment-chart-legend"><span><i/>Total Appointments</span><span><i/>Completed</span></div><div className="appointment-plot small"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} margin={{ top: 0, right: 10, left: -22, bottom: 0 }}><CartesianGrid stroke="#edf1f8" vertical={false}/><XAxis dataKey="date" tickFormatter={chartDate} minTickGap={25} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(v) => chartDate(String(v))}/><Bar isAnimationActive={false} dataKey="total" name="Total Appointments" fill="#1768ff" radius={[3, 3, 0, 0]}/><Bar isAnimationActive={false} dataKey="completed" name="Completed" fill="#3bd3a8" radius={[3, 3, 0, 0]}/></BarChart></ResponsiveContainer></div></article><Ranking title="Top Doctors by Appointments" rows={rank("doctorId")}/><Ranking title="Appointments by Department" rows={rank("departmentId")}/></div>
    </>}
  </>;
}
