import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, ExternalLink, PhoneCall, PhoneIncoming, PhoneOutgoing, Search } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { api, unwrap } from "../api";
import "./CallLogs.css";

const when = (value?: string) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";
const duration = (seconds = 0) => { const h = Math.floor(seconds / 3600), m = Math.floor((seconds % 3600) / 60), s = seconds % 60; return h ? `${h}h ${m}m ${s}s` : `${m}m ${s}s`; };

export function CallLogDetailsPage() {
  const navigate = useNavigate(), [routeParams] = useSearchParams(), user = JSON.parse(localStorage.getItem("user") || "{}"), staffPortal = user.portal === "STAFF";
  const [search, setSearch] = useState(""), [status, setStatus] = useState(""), [direction, setDirection] = useState(routeParams.get("direction") || ""), [page, setPage] = useState(1), [callingNumber, setCallingNumber] = useState("");
  const category = routeParams.get("category") || "", allTime = routeParams.get("allTime") === "true", start = routeParams.get("start") || "", end = routeParams.get("end") || "", agentId = routeParams.get("agentId") || "";
  const { data: profile } = useQuery({ queryKey: ["telecmi-me"], queryFn: () => api.get("/integrations/telecmi/me").then(unwrap) });
  const { data = { items: [], total: 0 }, isLoading, error } = useQuery({
    queryKey: ["telecmi-call-details", search, status, direction, category, allTime, start, end, agentId, page],
    queryFn: () => api.get("/integrations/telecmi/calls", { params: { search: search || undefined, status: status || undefined, category: status ? undefined : category || undefined, direction: direction || undefined, agentId: agentId || undefined, allTime: allTime ? "true" : undefined, startDate: !allTime && start ? new Date(`${start}T00:00:00`).toISOString() : undefined, endDate: !allTime && end ? new Date(`${end}T23:59:59.999`).toISOString() : undefined, page, limit: 25 } }).then(unwrap),
    refetchInterval: 15000,
  });
  const call = useMutation({ mutationFn: (to: string) => { setCallingNumber(to); return api.post("/integrations/telecmi/make-call", { to }); }, onSuccess: () => window.alert("TeleCMI call started. Answer your registered agent phone to connect."), onError: (callError: any) => window.alert(callError.response?.data?.message || "Unable to start the TeleCMI call."), onSettled: () => setCallingNumber("") });
  const totalPages = Math.max(1, Math.ceil((data.total || 0) / 25));
  const openRecording = async (url: string) => { if (/^https?:\/\//.test(url)) return void window.open(url, "_blank", "noopener,noreferrer"); const response = await api.get(url, { responseType: "blob" }), objectUrl = URL.createObjectURL(response.data); window.open(objectUrl, "_blank", "noopener,noreferrer"); window.setTimeout(() => URL.revokeObjectURL(objectUrl), 60000); };
  const heading = category === "ANSWERED" ? "Answered Calls" : category === "MISSED" ? "Missed Calls" : direction === "INBOUND" ? "Received Calls" : direction === "OUTBOUND" ? "Outgoing Calls" : "All Calls";

  return <><button type="button" className="call-details-back" onClick={() => navigate("/app/call-logs")}><ArrowLeft /> Back to call analytics</button><div className="page-head"><div><span>IVR &amp; CALL CENTRE</span><h1>{heading}</h1><p>{staffPortal ? "Your call history with click-to-call access." : "Detailed call history for the selected analytics block."}</p></div></div><section className="panel table-panel call-records">
    <div className="call-section-head caller-head"><div><span><PhoneCall /></span><div><h3>Call records</h3><p>{data.total || 0} matching call{data.total === 1 ? "" : "s"}</p></div></div></div>
    <div className="toolbar call-toolbar call-details-toolbar"><label className="search"><Search /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search phone, agent or call ID..." /></label><select value={direction} onChange={(e) => { setDirection(e.target.value); setPage(1); }}><option value="">All directions</option><option value="INBOUND">Inbound</option><option value="OUTBOUND">Outbound</option></select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{["RINGING", "ANSWERED", "COMPLETED", "MISSED", "ABANDONED", "FAILED", "UNKNOWN"].map((value) => <option key={value}>{value}</option>)}</select></div>
    {isLoading ? <div className="state">Loading TeleCMI calls…</div> : error ? <div className="state error">{(error as any).response?.data?.message || "Unable to load TeleCMI call logs."}</div> : data.items.length ? <div className="table-wrap"><table><thead><tr><th>#</th><th>Caller</th><th>Matched contact</th><th>Direction</th><th>Status</th><th>Agent</th><th>Started</th><th>Duration</th><th>Recording</th></tr></thead><tbody>{data.items.map((item: any, index: number) => <tr key={item.id}><td>{(page - 1) * 25 + index + 1}</td><td><div className="caller-number-actions"><span><b>{item.callerNumber}</b><small className="cell-sub">{item.externalId}</small></span>{staffPortal && profile?.canCall && <button type="button" className="click-to-call" disabled={call.isPending} onClick={() => call.mutate(item.callerNumber)} title={`Call ${item.callerNumber}`}><PhoneCall />{callingNumber === item.callerNumber ? "Calling…" : "Call"}</button>}</div></td><td><span className={`contact-badge ${item.patient || item.lead ? "matched" : "unmatched"}`}>{item.patient?.name || item.lead?.name || "Unmatched"}</span><small className="cell-sub">{item.patient?.patientNumber || item.lead?.leadNumber}</small></td><td><span className={`direction-badge ${item.direction.toLowerCase()}`}>{item.direction === "INBOUND" ? <PhoneIncoming /> : <PhoneOutgoing />}{item.direction}</span></td><td><span className={`call-badge ${item.status.toLowerCase()}`}>{item.status}</span></td><td>{item.agentName || "—"}</td><td>{when(item.startedAt || item.createdAt)}</td><td>{duration(item.durationSeconds)}</td><td>{item.recordingUrl ? <button type="button" className="recording-link" onClick={() => openRecording(item.recordingUrl)}><ExternalLink size={15} /> Open</button> : "—"}</td></tr>)}</tbody></table></div> : <div className="empty"><PhoneCall /><h3>No calls found</h3><p>Try another filter or date range.</p></div>}
    <div className="call-pagination"><span>Showing {data.items.length ? (page - 1) * 25 + 1 : 0} to {Math.min(page * 25, data.total)} of {data.total} calls</span>{totalPages > 1 && <nav aria-label="Call pagination"><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span><button type="button" className="active">{page}</button></span><button type="button" disabled={page === totalPages} onClick={() => setPage(page + 1)}>Next</button></nav>}</div>
  </section></>;
}
