import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, ExternalLink, PhoneCall, Search } from "lucide-react";
import { api, unwrap } from "../api";

const when=(value?:string)=>value?new Date(value).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—";
const duration=(seconds?:number)=>seconds===undefined||seconds===null?"—":`${Math.floor(seconds/60)}m ${seconds%60}s`;

export function CallLogsPage(){
  const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[direction,setDirection]=useState("");
  const {data={items:[],total:0},isLoading,error}=useQuery({queryKey:["telecmi-calls",search,status,direction],queryFn:()=>api.get("/integrations/telecmi/calls",{params:{search:search||undefined,status:status||undefined,direction:direction||undefined}}).then(unwrap)});
  const exportCsv=()=>{const rows=[["Call ID","Caller","Contact","Direction","Status","Agent","Started","Duration","Disposition"],...data.items.map((call:any)=>[call.externalId,call.callerNumber,call.patient?.name||call.lead?.name||"",call.direction,call.status,call.agentName||"",when(call.startedAt),call.durationSeconds??"",call.disposition||""])],csv=rows.map((row:any[])=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));link.download="telecmi-call-logs.csv";link.click();URL.revokeObjectURL(link.href)};
  return <><div className="page-head"><div><span>IVR &amp; CALL CENTRE</span><h1>TeleCMI Call Logs</h1><p>Incoming and outgoing calls, recordings and CRM contact matching in one place.</p></div><button className="btn" onClick={exportCsv}><Download/>Export CSV</button></div><section className="panel table-panel"><div className="toolbar call-toolbar"><label className="search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search phone, agent or call ID..."/></label><select value={direction} onChange={event=>setDirection(event.target.value)}><option value="">All directions</option><option value="INBOUND">Inbound</option><option value="OUTBOUND">Outbound</option></select><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">All statuses</option>{["RINGING","ANSWERED","COMPLETED","MISSED","ABANDONED","FAILED","UNKNOWN"].map(value=><option key={value}>{value}</option>)}</select></div>{isLoading?<div className="state">Loading TeleCMI calls…</div>:error?<div className="state error">Unable to load TeleCMI call logs.</div>:data.items.length?<div className="table-wrap"><table><thead><tr><th>Caller</th><th>Matched contact</th><th>Direction</th><th>Status</th><th>Agent</th><th>Started</th><th>Duration</th><th>Recording</th></tr></thead><tbody>{data.items.map((call:any)=><tr key={call.id}><td><b>{call.callerNumber}</b><small className="cell-sub">{call.externalId}</small></td><td>{call.patient?.name||call.lead?.name||"Unmatched"}<small className="cell-sub">{call.patient?.patientNumber||call.lead?.leadNumber}</small></td><td>{call.direction}</td><td><span className={`call-badge ${call.status.toLowerCase()}`}>{call.status}</span></td><td>{call.agentName||"—"}</td><td>{when(call.startedAt||call.createdAt)}</td><td>{duration(call.durationSeconds)}</td><td>{call.recordingUrl?<a className="recording-link" href={call.recordingUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open</a>:"—"}</td></tr>)}</tbody></table></div>:<div className="empty"><PhoneCall/><h3>No TeleCMI calls yet</h3><p>Configure TeleCMI in Super Admin, then synchronize reports or register the webhook.</p></div>}<div className="call-total">{data.total} call{data.total===1?"":"s"}</div></section></>;
}
