import {useQuery} from '@tanstack/react-query';
import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api,unwrap} from '../api';
import {Activity,AlarmClock,BarChart3,Bell,CalendarDays,CalendarPlus,IndianRupee,MessageCircle,Phone,Plus,UserPlus,Users,WalletCards} from 'lucide-react';
import './Dashboard.css';
import './DashboardRestricted.css';
const money=(n:any)=>`₹ ${Number(n||0).toLocaleString('en-IN')}`,time=(d:any)=>new Date(d).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}),todayLabel=()=>new Date().toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',weekday:'short',day:'2-digit',month:'short',year:'numeric'}),statusLabel=(v:string)=>String(v||'').replaceAll('_',' ');
export function Dashboard({mode}:{mode:'tenant'|'admin'}){const user=JSON.parse(localStorage.getItem('user')||'{}'),staff=mode==='tenant'&&user.portal==='STAFF',permissions=new Set<string>(user.permissions||[]),allowed=!staff||permissions.has('dashboard.read')||permissions.has('dashboard.manage'),{data={},isLoading}=useQuery({queryKey:['dashboard',mode],queryFn:()=>api.get(mode==='admin'?'/super-admin/dashboard':'/crm/dashboard').then(unwrap),enabled:mode==='admin'||allowed,refetchInterval:30000});if(mode==='tenant'&&!allowed)return <RestrictedDashboard fallback={user}/>;if(mode==='tenant')return <TenantDashboard data={data} loading={isLoading}/>;const stats=[['Total tenants',data.totalTenants,Users],['Active tenants',data.activeTenants,Activity],['Pending approvals',data.pendingApprovals,Bell],['Total leads',data.totalLeads,Users],['Appointments',data.totalAppointments,CalendarDays]];return <><div className="page-head"><div><span>PLATFORM OVERVIEW</span><h1>Super Admin Dashboard</h1><p>Monitor your SaaS business and clinic network.</p></div></div><div className="stat-grid">{stats.map(([label,value,I]:any)=><article key={label}><div><small>{label}</small><b>{isLoading?'—':value??0}</b><span>Live data</span></div><I/></article>)}</div></>}
function RestrictedDashboard({fallback}:{fallback:any}){const{data}=useQuery({queryKey:['my-profile'],queryFn:()=>api.get('/auth/me').then(unwrap)}),profile=data||fallback;return <div className="restricted-dashboard"><section><div className="restricted-avatar">{String(profile.name||'S').charAt(0).toUpperCase()}</div><div><small>STAFF PROFILE</small><h2>{profile.name||'Staff'}</h2><dl><div><dt>Email</dt><dd>{profile.email||'—'}</dd></div><div><dt>Phone number</dt><dd>{profile.mobile||'—'}</dd></div></dl></div></section></div>}
function LiveGreeting({name}:{name:string}){const[now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(timer)},[]);const hour=Number(new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',hourCycle:'h23'}).format(now)),period=hour>=5&&hour<12?['Good morning','☀️']:hour>=12&&hour<17?['Good afternoon','🌤️']:hour>=17&&hour<21?['Good evening','🌇']:['Good night','🌙'],clock=now.toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit'});return <div><h1>{period[0]}, {name} <span>{period[1]}</span></h1><p>Here’s your clinic operations at a glance.</p><time className="ops-live-time">{todayLabel()} · {clock} IST</time></div>}
function QuickActions({navigate}:{navigate:(path:string)=>void}){const actions=[["New Patient",UserPlus,"/app/patients","blue"],["New Enquiry",Plus,"/app/leads","teal"],["Book Appointment",CalendarPlus,"/app/appointments/new","orange"],["Send WhatsApp",MessageCircle,"/app/whatsapp","green"],["Set Follow-up",AlarmClock,"/app/patient-followups","red"]] as const;return <section className="ops-quick"><header><h2><Plus/>Quick Actions</h2></header><div>{actions.map(([label,Icon,path,color])=><button key={label} onClick={()=>navigate(path)}><Icon className={color}/><span>{label}</span></button>)}</div></section>}
function TenantDashboard({data,loading}:{data:any;loading:boolean}){const nav=useNavigate(),user=JSON.parse(localStorage.getItem('user')||'{}'),metrics=[['Total Calls',data.todayCalls,Phone,'blue'],['New Enquiries',data.newEnquiriesToday,Users,'teal'],['Appointments',data.todayAppointments,CalendarDays,'orange'],['Patients Served',data.patientsServed,Users,'purple'],['Revenue Collected',money(data.revenueToday),IndianRupee,'green'],['Follow-ups Due',data.pendingFollowups,Bell,'red']];return <div className="ops-dashboard"><header className="ops-welcome"><LiveGreeting name={user.name?.split(' ')[0]||'Admin'}/><button className="ops-new" onClick={()=>nav('/app/leads')}><Plus/>New Enquiry</button></header><div className="ops-metrics">{metrics.map(([label,value,Icon,color]:any)=><article key={label}><Icon className={color}/><div><small>{label}</small><strong>{loading?'—':value??0}</strong><em className={color==='red'?'down':''}>{label==='Follow-ups Due'?`${data.overdueFollowups||0} overdue`:'Live clinic data'}</em></div><MiniSpark color={color}/></article>)}</div><div className="ops-row ops-overview-row"><Panel title="Enquiry & Appointment Overview" icon={<BarChart3/>} action={todayLabel()}><OverviewChart rows={data.todayOverview||[]}/></Panel><Panel title="Lead Conversion" icon={<Activity/>} action="Today"><LeadFunnel pipeline={data.pipeline||{}}/></Panel></div><div className="ops-row ops-middle-row"><Panel title="Today’s Appointment Schedule" icon={<CalendarDays/>} link={()=>nav('/app/calendar')}><AppointmentTable rows={data.todaySchedule||[]}/></Panel><Panel title="Department Load" icon={<Activity/>} action="Today"><DepartmentLoad rows={data.departmentLoad||[]}/></Panel></div><div className="ops-row ops-bottom-row"><Panel title="Call Centre Performance" icon={<Phone/>} action="Today"><CallPerformance rows={data.callCentrePerformance||[]}/></Panel><Panel title="Priority Follow-ups" icon={<Bell/>} link={()=>nav('/app/patient-followups')}><Followups rows={data.priorityFollowups||[]}/></Panel><Panel title="Recent Payments" icon={<WalletCards/>} link={()=>nav('/app/payments')}><Payments rows={data.todayPayments||[]}/></Panel></div><QuickActions navigate={nav}/></div>}
function Panel({title,icon,action,link,children}:{title:string;icon:React.ReactNode;action?:string;link?:()=>void;children:React.ReactNode}){return <section className="ops-panel"><header><h2>{icon}{title}</h2>{link?<button onClick={link}>View all</button>:action?<span>{action}⌄</span>:null}</header>{children}</section>}
function MiniSpark({color}:{color:string}){return <svg className={`mini-spark ${color}`} viewBox="0 0 52 24"><polyline points="1,20 9,15 16,18 24,8 32,12 40,4 50,7"/></svg>}
function OverviewChart({rows}:{rows:any[]}){const max=Math.max(1,...rows.flatMap(x=>[x.calls,x.enquiries,x.appointments])),points=(key:string)=>rows.map((x,i)=>`${18+i*43},${112-(Number(x[key]||0)/max)*88}`).join(' ');return <div className="overview-chart"><div className="chart-legend"><i className="calls"/>Calls <i className="enquiries"/>Enquiries <i className="appointments"/>Appointments</div><svg viewBox="0 0 510 145" preserveAspectRatio="none"><g className="grid">{[24,46,68,90,112].map(y=><line key={y} x1="18" y1={y} x2="491" y2={y}/>)}</g><polyline className="calls" points={points('calls')}/><polyline className="enquiries" points={points('enquiries')}/><polyline className="appointments" points={points('appointments')}/>{rows.map((x,i)=><text key={x.hour} x={18+i*43} y="136">{x.hour>12?x.hour-12:x.hour} {x.hour>=12?'PM':'AM'}</text>)}</svg></div>}
function LeadFunnel({pipeline}:{pipeline:any}){const stages=[['NEW','New Enquiries','blue'],['CONTACTED','Contacted','cyan'],['INTERESTED','Interested','green'],['APPOINTMENT_PENDING','Appointment','orange'],['CONVERTED','Converted','red']],total=Object.values(pipeline).reduce((a:number,v:any)=>a+Number(v),0);return <div className="lead-funnel"><div className="funnel-shape">{stages.map(([,label,color])=><i className={color} key={label}/>)}</div><div className="funnel-data">{stages.map(([key,label,color])=><div key={key}><i className={color}/><span>{label}</span><b>{pipeline[key]||0}</b><small>{total?Math.round((pipeline[key]||0)*100/total):0}%</small></div>)}</div></div>}
function AppointmentTable({rows}:{rows:any[]}){return <Table empty="No appointments today" heads={['Time','Patient','Doctor / Specialist','Department','Payment','Status']} rows={rows.slice(0,5).map(x=>[time(x.startsAt),<b>{x.patient?.name}<small>{x.appointmentNumber}</small></b>,x.doctor?.name,x.department?.name,<Tag value={x.paymentStatus}/>,<Tag value={x.status}/>])}/>}
function DepartmentLoad({rows}:{rows:any[]}){const max=Math.max(1,...rows.map(x=>x.bookings));return <div className="department-load">{rows.length?rows.slice(0,5).map((x,i)=><div key={x.name}><span>{x.name}</span><b>{x.bookings}</b><em><i style={{width:`${Math.round(x.bookings*100/max)}%`}} className={`bar-${i}`}/></em><small>{Math.round(x.bookings*100/max)}%</small></div>):<Empty text="No department bookings today"/>}</div>}
function CallPerformance({rows}:{rows:any[]}){return <Table empty="No calls today" heads={['Agent','Calls','Answered','Missed','Avg. Duration','Answer Rate']} rows={rows.slice(0,5).map(x=>[x.name,x.calls,x.answered,x.missed,`${Math.floor((x.durationSeconds/Math.max(1,x.calls))/60)}m ${Math.round((x.durationSeconds/Math.max(1,x.calls))%60)}s`,<Rate value={Math.round(x.answered*100/Math.max(1,x.calls))}/>])}/>}
function Followups({rows}:{rows:any[]}){return <Table empty="No follow-ups due" heads={['Patient','Reason','Due Time','Action']} rows={rows.slice(0,5).map(x=>[x.patient?.name||x.lead?.name||'Unmatched',x.remarks||x.type,time(x.scheduledAt),<button className="call-action" onClick={()=>x.patient?.mobile&&window.dispatchEvent(new CustomEvent('telecmi:dial',{detail:{number:x.patient.mobile}}))}><Phone/></button>])}/>}
function Payments({rows}:{rows:any[]}){return <Table empty="No payments today" heads={['Patient','Amount','Method','Time']} rows={rows.slice(0,5).map(x=>[x.appointment?.patient?.name||'—',money(x.amount),x.provider,time(x.confirmedAt||x.createdAt)])}/>}
function Table({heads,rows,empty}:{heads:string[];rows:any[][];empty:string}){if(!rows.length)return <Empty text={empty}/>;return <div className="ops-table"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x||'—'}</td>)}</tr>)}</tbody></table></div>}
function Tag({value}:{value:string}){return <span className={`ops-tag ${String(value).toLowerCase()}`}>{statusLabel(value)}</span>}
function Rate({value}:{value:number}){return <div className="rate"><i><b style={{width:`${value}%`}}/></i><span>{value}%</span></div>}
function Empty({text}:{text:string}){return <div className="ops-empty"><AlarmClock/>{text}</div>}
