import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, FileText, FlaskConical, Plus, ScanLine, Search, Trash2, Upload, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { api, unwrap } from "../api";

type Kind = "lab" | "radiology";
type Patient = { id:string;name:string;mobile?:string;patientNumber?:string };
type Test = { id:string;title:string;data?:{code?:string;price?:number} };
type Prescription = { name:string;type:string;size:number;dataUrl:string };
export function DiagnosticAppointmentBookingPage({kind}:{kind:Kind}){
 const nav=useNavigate(),isLab=kind==="lab",label=isLab?"Lab":"Radiology",testLabel=isLab?"Pathology":"Radiology";
 const [patientSearch,setPatientSearch]=useState(""),[patient,setPatient]=useState<Patient|null>(null),[patientOpen,setPatientOpen]=useState(false),[testSearch,setTestSearch]=useState(""),[testOpen,setTestOpen]=useState(false),[selected,setSelected]=useState<Test[]>([]),[discount,setDiscount]=useState(0),[prescription,setPrescription]=useState<Prescription|null>(null),[fileError,setFileError]=useState("");
 const {data:patientData}=useQuery({queryKey:["booking-patients"],queryFn:()=>api.get("/crm/patients?limit=100").then(unwrap)}),{data:testData}=useQuery({queryKey:[`${kind}-booking-tests`],queryFn:()=>api.get(`/crm/modules/${kind}-tests?limit=100`).then(unwrap)});
 const patients:Patient[]=patientData?.items||[],tests:Test[]=testData?.items||[];
 const patientMatches=patients.filter(item=>[item.name,item.mobile,item.patientNumber].some(value=>String(value||"").toLowerCase().includes(patientSearch.toLowerCase()))).slice(0,10);
 const testMatches=tests.filter(item=>!selected.some(chosen=>chosen.id===item.id)&&[item.title,item.data?.code].some(value=>String(value||"").toLowerCase().includes(testSearch.toLowerCase()))).slice(0,12);
 const subtotal=useMemo(()=>selected.reduce((sum,test)=>sum+Number(test.data?.price||0),0),[selected]),total=Math.max(0,subtotal-Number(discount||0));
 const save=useMutation({mutationFn:(payload:Record<string,unknown>)=>api.post(`/crm/modules/${kind}-appointments`,payload),onSuccess:()=>nav(`/app/${kind}-appointments`)});
 const uploadPrescription=(file?:File)=>{setFileError("");if(!file)return;const allowed=["image/jpeg","image/png","image/webp","application/pdf"];if(!allowed.includes(file.type)){setFileError("Upload a JPG, PNG, WebP or PDF prescription.");return}if(file.size>4*1024*1024){setFileError("Prescription must be smaller than 4 MB.");return}const reader=new FileReader();reader.onload=()=>setPrescription({name:file.name,type:file.type,size:file.size,dataUrl:String(reader.result)});reader.onerror=()=>setFileError("Unable to read this file.");reader.readAsDataURL(file)};
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!patient||!selected.length)return;const form=Object.fromEntries(new FormData(event.currentTarget));save.mutate({...form,title:`${label.toUpperCase()}-${Date.now().toString(36).toUpperCase()}`,patientId:patient.id,testIds:selected.map(test=>test.id),testNames:selected.map(test=>test.title).join(", "),tests:selected.map(test=>({id:test.id,title:test.title,price:Number(test.data?.price||0)})),subtotal,discountAmount:Number(discount||0),amount:total,currency:"INR",prescription})};
 return <div className="diagnostic-booking"><button className="schedule-back" onClick={()=>nav(`/app/${kind}-appointments`)}><ArrowLeft/> Back to {label} Appointments</button><div className="schedule-title"><div><span>CLINIC MANAGEMENT</span><h1>New {label} Appointment</h1><p>Select one patient and multiple {testLabel.toLowerCase()} tests.</p></div>{isLab?<FlaskConical/>:<ScanLine/>}</div><form onSubmit={submit} className="diagnostic-booking-grid"><section className="panel diagnostic-form"><h2>Patient and appointment</h2><label>Patient *</label><div className="patient-search"><div className="smart-select-input"><Search/><input value={patientSearch} placeholder="Search patient name, mobile or ID" onFocus={()=>setPatientOpen(true)} onBlur={()=>setTimeout(()=>setPatientOpen(false),150)} onChange={event=>{setPatientSearch(event.target.value);setPatient(null);setPatientOpen(true)}}/></div>{patientOpen&&<div className="patient-results">{patientMatches.map(item=><button type="button" key={item.id} onMouseDown={()=>{setPatient(item);setPatientSearch(`${item.name} · ${item.mobile||item.patientNumber}`);setPatientOpen(false)}}><strong>{item.name}</strong><span>{item.mobile}</span><small>{item.patientNumber}</small></button>)}</div>}{patient&&<small className="patient-selected">Patient selected</small>}</div><div className="diagnostic-fields"><label>Appointment date and time *<input name="appointmentAt" type="datetime-local" required/></label>{isLab&&<label>Sample collection time<input name="sampleCollectionAt" type="datetime-local"/></label>}<label>Priority<select name="priority"><option>ROUTINE</option><option>URGENT</option><option>{isLab?"STAT":"EMERGENCY"}</option></select></label><label>Payment status<select name="paymentStatus"><option>PENDING</option><option>PAID</option><option>PARTIALLY_PAID</option></select></label><label>Status<select name="status"><option>BOOKED</option><option>{isLab?"SAMPLE_PENDING":"ARRIVED"}</option><option>IN_PROGRESS</option><option>COMPLETED</option></select></label><label className="wide">Instructions<textarea name="instructions"/></label></div><div className="prescription-upload"><h3>Prescription</h3><p>Upload the referring doctor’s prescription (JPG, PNG, WebP or PDF, maximum 4 MB).</p>{prescription?<div className="prescription-preview">{prescription.type.startsWith("image/")?<img src={prescription.dataUrl} alt="Prescription preview"/>:<FileText/>}<div><b>{prescription.name}</b><small>{(prescription.size/1024).toFixed(1)} KB</small></div><button type="button" onClick={()=>setPrescription(null)}><X/></button></div>:<label className="upload-drop"><Upload/><span><b>Choose prescription</b><small>Click to browse from this device</small></span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event=>uploadPrescription(event.target.files?.[0])}/></label>}{fileError&&<div className="alert error">{fileError}</div>}</div></section>
 <aside className="panel test-cart"><h2>{testLabel} tests</h2><div className="patient-search"><div className="smart-select-input"><Search/><input value={testSearch} placeholder={`Search and add ${testLabel.toLowerCase()} tests`} onFocus={()=>setTestOpen(true)} onBlur={()=>setTimeout(()=>setTestOpen(false),150)} onChange={event=>{setTestSearch(event.target.value);setTestOpen(true)}}/></div>{testOpen&&<div className="patient-results">{testMatches.map(test=><button type="button" key={test.id} onMouseDown={()=>{setSelected(items=>[...items,test]);setTestSearch("");setTestOpen(false)}}><strong>{test.title}</strong><span>₹{Number(test.data?.price||0).toLocaleString("en-IN")}</span><small>{test.data?.code}</small></button>)}</div>}</div><div className="selected-tests">{selected.map(test=><article key={test.id}><div><b>{test.title}</b><small>{test.data?.code}</small></div><strong>₹{Number(test.data?.price||0).toLocaleString("en-IN")}</strong><button type="button" onClick={()=>setSelected(items=>items.filter(item=>item.id!==test.id))}><Trash2/></button></article>)}{!selected.length&&<p>Search and add one or more tests.</p>}</div><div className="booking-totals"><p><span>Subtotal</span><b>₹{subtotal.toLocaleString("en-IN")}</b></p><label>Discount amount<input type="number" min="0" max={subtotal} value={discount} onChange={event=>setDiscount(Number(event.target.value))}/></label><p className="grand-total"><span>Total payable</span><b>₹{total.toLocaleString("en-IN")}</b></p></div>{save.error&&<div className="alert error">Unable to save appointment.</div>}<button className="btn full" disabled={!patient||!selected.length||save.isPending}><Plus/>{save.isPending?"Saving…":`Book ${label} Appointment`}</button></aside></form></div>;
}
