import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, Filter, Search, WalletCards } from "lucide-react";
import { api, unwrap } from "../api";
type Log = { id:string;serviceType:string;serviceName:string;customerName:string;customerMobile?:string;patientNumber?:string;appointmentNumber:string;provider:string;transactionId?:string;amount:number;currency:string;status:string;date:string };
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());
export function PaymentLogsPage(){
 const [search,setSearch]=useState(""),[type,setType]=useState("ALL"),[service,setService]=useState("ALL"),[status,setStatus]=useState("ALL"),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const {data,isLoading,error}=useQuery({queryKey:["payment-logs"],queryFn:()=>api.get("/crm/payment-logs").then(unwrap)}),rows:Log[]=data?.items||[];
 const services=[...new Set(rows.filter(row=>type==="ALL"||row.serviceType===type).map(row=>row.serviceName))].sort(),statuses=[...new Set(rows.map(row=>row.status))].sort();
 const filtered=useMemo(()=>rows.filter(row=>{const date=new Date(row.date),query=search.toLowerCase().trim();return(type==="ALL"||row.serviceType===type)&&(service==="ALL"||row.serviceName===service)&&(status==="ALL"||row.status===status)&&(!from||date>=new Date(`${from}T00:00:00`))&&(!to||date<=new Date(`${to}T23:59:59`))&&(!query||[row.customerName,row.customerMobile,row.patientNumber,row.appointmentNumber,row.serviceName,row.provider,row.transactionId,row.status].some(value=>String(value||"").toLowerCase().includes(query)))}),[from,rows,search,service,status,to,type]);
 const download=()=>{const headings=["Date","Customer","Mobile","Patient ID","Type","Doctor / Test","Appointment","Method","Transaction","Amount","Status"],csv=[headings,...filtered.map(row=>[new Date(row.date).toLocaleString("en-IN"),row.customerName,row.customerMobile||"",row.patientNumber||"",row.serviceType,row.serviceName,row.appointmentNumber,row.provider,row.transactionId||"",row.amount,row.status])].map(line=>line.map(cell=>`"${String(cell).replaceAll('"','""')}"`).join(",")).join("\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));link.download="payment-logs.csv";link.click();URL.revokeObjectURL(link.href)};
 const total=filtered.reduce((sum,row)=>sum+Number(row.amount||0),0);
 return <div><div className="page-head"><div><span>FINANCE</span><h1>Payment Logs</h1><p>All doctor, laboratory and radiology payment records in one place.</p></div><button className="btn ghost" onClick={download}><Download/> Export CSV</button></div><div className="payment-summary"><article><WalletCards/><div><small>Filtered records</small><b>{filtered.length}</b></div></article><article><WalletCards/><div><small>Filtered amount</small><b>₹{total.toLocaleString("en-IN")}</b></div></article></div>
 <section className="panel table-panel"><div className="payment-filters"><div className="search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search customer, mobile, patient ID, doctor, test, transaction…"/></div><label><Filter/><select value={type} onChange={event=>{setType(event.target.value);setService("ALL")}}><option value="ALL">All service types</option><option value="DOCTOR">Doctor</option><option value="LAB">Lab</option><option value="RADIOLOGY">Radiology</option></select></label><label><select value={service} onChange={event=>setService(event.target.value)}><option value="ALL">All doctors/tests</option>{services.map(item=><option key={item}>{item}</option>)}</select></label><label><select value={status} onChange={event=>setStatus(event.target.value)}><option value="ALL">All payment statuses</option>{statuses.map(item=><option key={item}>{label(item)}</option>)}</select></label><label className="date-filter">From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label className="date-filter">To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></div>
 {isLoading?<div className="state">Loading payment logs…</div>:error?<div className="state error">Unable to load payment logs.</div>:<div className="table-wrap"><table><thead><tr>{["Date","Customer","Service Type","Doctor / Test","Appointment","Method / Transaction","Amount","Status"].map(heading=><th key={heading}>{heading}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={`${row.serviceType}-${row.id}`}><td>{new Date(row.date).toLocaleString("en-IN")}</td><td><b>{row.customerName}</b><small className="cell-sub">{row.customerMobile||row.patientNumber||"—"}</small></td><td><span className={`service-pill ${row.serviceType.toLowerCase()}`}>{label(row.serviceType)}</span></td><td>{row.serviceName}</td><td>{row.appointmentNumber}</td><td>{label(row.provider)}<small className="cell-sub">{row.transactionId||"No reference"}</small></td><td><b>{row.currency} {Number(row.amount).toLocaleString("en-IN")}</b></td><td><span className="status-pill">{label(row.status)}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><WalletCards/><p>No matching payment logs found.</p></div>}</div>}</section></div>;
}
