import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, KeyRound, PhoneCall, RefreshCw, Save } from "lucide-react";
import { api, unwrap } from "../api";

const defaults={appId:"",appSecret:"",businessNumber:"",apiUrl:"https://rest.telecmi.com/v2",webhookUrl:"",isTestMode:false,isActive:true};

export function TelecmiIntegrationsPage(){
  const client=useQueryClient();
  const {data:tenants=[],isLoading,error}=useQuery({queryKey:["admin-telecmi-integrations"],queryFn:()=>api.get("/super-admin/telecmi-integrations").then(unwrap)});
  const today=new Date().toISOString().slice(0,10),prior=new Date(Date.now()-30*86400000).toISOString().slice(0,10);
  const [tenantId,setTenantId]=useState(""),[form,setForm]=useState(defaults),[from,setFrom]=useState(prior),[to,setTo]=useState(today);
  const {data:report={summary:[],calls:[]},isLoading:reportLoading}=useQuery({queryKey:["admin-telecmi-report",from,to],queryFn:()=>api.get("/super-admin/telecmi-report",{params:{from:`${from}T00:00:00.000Z`,to:`${to}T23:59:59.999Z`}}).then(unwrap)});
  const selected=useMemo(()=>tenants.find((tenant:any)=>tenant.id===tenantId),[tenants,tenantId]);
  const {data:accountReport,error:accountError,isFetching:accountLoading,refetch:loadAccountReport}=useQuery({queryKey:["admin-telecmi-account-report",tenantId,from,to],queryFn:()=>api.get(`/super-admin/tenants/${tenantId}/telecmi/account-report`,{params:{from:`${from}T00:00:00.000Z`,to:`${to}T23:59:59.999Z`}}).then(unwrap),enabled:false});
  useEffect(()=>{if(!tenantId&&tenants.length)setTenantId(tenants[0].id)},[tenants,tenantId]);
  useEffect(()=>{if(selected)setForm({...defaults,...(selected.integration||{}),appSecret:""})},[selected]);
  const save=useMutation({mutationFn:()=>api.put(`/super-admin/tenants/${tenantId}/telecmi`,form),onSuccess:async()=>client.invalidateQueries({queryKey:["admin-telecmi-integrations"]})});
  const sync=useMutation({mutationFn:()=>api.post(`/super-admin/tenants/${tenantId}/telecmi/sync`,{startDate:`${from}T00:00:00.000Z`,endDate:`${to}T23:59:59.999Z`}),onSuccess:async(response:any)=>{await client.invalidateQueries({queryKey:["admin-telecmi-report"]});window.alert(`${response.data.data.synced} TeleCMI call records synchronized.`)}});
  const field=(name:keyof typeof defaults,value:string|boolean)=>setForm(current=>({...current,[name]:value}));
  return <><div className="page-head"><div><span>SAAS INTEGRATIONS</span><h1>TeleCMI Voice</h1><p>Configure isolated TeleCMI application credentials for each clinic.</p></div></div><div className="integration-layout">
    <aside className="panel clinic-picker"><h3>Clinics</h3><p>Select the clinic whose TeleCMI account you want to configure.</p>{isLoading?<div className="state">Loading clinics…</div>:error?<div className="alert error">{(error as any).response?.data?.message||"Unable to load clinics"}</div>:tenants.length?tenants.map((tenant:any)=><button type="button" className={tenant.id===tenantId?"active":""} key={tenant.id} onClick={()=>setTenantId(tenant.id)}><span>{tenant.name}<small>{tenant.email}</small></span>{tenant.integration?.isActive&&<CheckCircle2/>}</button>):<div className="state">No clinics found.</div>}</aside>
    {selected&&<form className="panel integration-form" onSubmit={event=>{event.preventDefault();save.mutate()}}><div className="integration-title"><PhoneCall/><div><h2>{selected.name}</h2><p>{selected.integration?"TeleCMI is configured for this clinic.":"Add this clinic's TeleCMI App ID and App Secret."}</p></div><label className="toggle-label"><input type="checkbox" checked={form.isActive} onChange={event=>field("isActive",event.target.checked)}/> Active</label></div><div className="integration-grid">
      <label><span>App ID</span><input required value={form.appId} placeholder="TeleCMI App ID" onChange={event=>field("appId",event.target.value)}/></label>
      <label><span>Business number</span><input required value={form.businessNumber} placeholder="TeleCMI business / virtual number" onChange={event=>field("businessNumber",event.target.value)}/></label>
      <label className="wide"><span><KeyRound/> App Secret</span><input type="password" required={!selected.integration?.hasAppSecret} value={form.appSecret} placeholder={selected.integration?.hasAppSecret?"Saved securely — leave blank to keep it":"Paste this clinic's TeleCMI App Secret"} autoComplete="new-password" onChange={event=>field("appSecret",event.target.value)}/><small>The App Secret is encrypted and is never returned to the browser.</small></label>
      <label className="wide"><span>TeleCMI API URL</span><input type="url" required value={form.apiUrl} onChange={event=>field("apiUrl",event.target.value)}/></label>
      <label className="wide"><span>Webhook URL (optional)</span><input type="url" value={form.webhookUrl} placeholder="https://crm.example.com/api/integrations/telecmi/webhook" onChange={event=>field("webhookUrl",event.target.value)}/><small>Configure this URL under TeleCMI Settings → Webhooks for live CDR events.</small></label>
      <label className="toggle-label"><input type="checkbox" checked={form.isTestMode} onChange={event=>field("isTestMode",event.target.checked)}/> Test mode</label>
    </div>{save.isSuccess&&<div className="alert settings-success">TeleCMI configuration saved for {selected.name}.</div>}{save.error&&<div className="alert error">{(save.error as any).response?.data?.message||"Unable to save TeleCMI configuration"}</div>}<div className="modal-actions"><button className="btn" disabled={save.isPending}><Save/>{save.isPending?"Saving…":"Save integration"}</button></div></form>}
  </div><section className="panel table-panel telecmi-report"><div className="page-head"><div><span>ALL CLINICS</span><h2>TeleCMI Call Report</h2><p>Incoming, outgoing, answered and missed call records synchronized from TeleCMI.</p></div><div className="page-actions"><label>From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="btn ghost" disabled={!selected?.integration||accountLoading} onClick={()=>loadAccountReport()}>{accountLoading?"Loading…":"Balance & analysis"}</button><button className="btn" disabled={!selected?.integration||sync.isPending} onClick={()=>sync.mutate()}><RefreshCw/>{sync.isPending?"Synchronizing…":`Sync ${selected?.name||"clinic"}`}</button></div></div>{accountError&&<div className="alert error">{(accountError as any).response?.data?.message||"Unable to retrieve TeleCMI account report"}</div>}{accountReport&&<div className="stat-grid"><article><div><small>Answered calls</small><b>{accountReport.analysis?.answered??0}</b><span>TeleCMI live analysis</span></div><PhoneCall/></article><article><div><small>Missed calls</small><b>{accountReport.analysis?.missed??0}</b><span>{accountReport.analysis?.total??0} total calls</span></div><PhoneCall/></article><article><div><small>Main balance</small><b>{accountReport.balance?.balance??0}</b><span>SMS balance: {accountReport.balance?.sms??0}</span></div><PhoneCall/></article></div>}{sync.error&&<div className="alert error">{(sync.error as any).response?.data?.message||"Unable to synchronize TeleCMI reports"}</div>}{reportLoading?<div className="state">Loading TeleCMI reports…</div>:<><div className="stat-grid">{report.summary.map((row:any)=><article key={row.tenantId}><div><small>{row.clinic}</small><b>{row.total}</b><span>{row.answered} answered · {row.missed} missed · {row.inbound} incoming · {row.outbound} outgoing</span></div><PhoneCall/></article>)}</div><div className="table-wrap"><table><thead><tr><th>Clinic</th><th>Call ID</th><th>Caller</th><th>Contact</th><th>Direction</th><th>Status</th><th>Agent</th><th>Started</th><th>Duration</th></tr></thead><tbody>{report.calls.map((call:any)=><tr key={call.id}><td>{call.tenant?.name}</td><td>{call.externalId}</td><td>{call.callerNumber}</td><td>{call.patient?.name||call.lead?.name||"Unmatched"}</td><td>{call.direction}</td><td>{call.status}</td><td>{call.agentName||"—"}</td><td>{call.startedAt?new Date(call.startedAt).toLocaleString("en-IN"):"—"}</td><td>{call.durationSeconds??0}s</td></tr>)}</tbody></table></div></>}</section></>;
}
